apiVersion: source.toolkit.fluxcd.io/v1beta2
kind: HelmRepository
metadata:
  name: trivy-exporter
  namespace: trivy-system
spec:
  interval: 60m
  url: https://giantswarm.github.io/giantswarm-catalog

---

apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: trivy-exporter
  namespace: trivy-system
spec:
  chart:
    spec:
      chart: starboard-exporter
      sourceRef:
        kind: HelmRepository
        name: trivy-exporter
      version: 0.4.1
  interval: 60m0s